<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Anfragen\Module'                        => __DIR__ . '/Module.php',
    'Anfragen\Controller\AnfragenController' => __DIR__ . '/src/Anfragen/Controller/AnfragenController.php',
    
);
