<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Strecke\Module'                        => __DIR__ . '/Module.php',
    'Strecke\Controller\StreckeController' => __DIR__ . '/src/Strecke/Controller/StreckeController.php',
    'VeranstaltungTest\Framework\TestCase'        => __DIR__ . '/tests/Veranstaltung/Framework/TestCase.php',
    'VeranstaltungTest\SampleTest'                => __DIR__ . '/tests/Veranstaltung/SampleTest.php',
);
