<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Suche\Module'                        => __DIR__ . '/Module.php',
    'Suche\Controller\SucheController' => __DIR__ . '/src/Suche/Controller/SucheController.php',
    'SucheTest\Framework\TestCase'        => __DIR__ . '/tests/Suche/Framework/TestCase.php',
    'SucheTest\SampleTest'                => __DIR__ . '/tests/Suche/SampleTest.php',
);
