<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Cashback-Aktionen';
$this->headTitle($title);
?>
<b>
<?php 
if ($this->flashMessenger()->hasMessages())
{
    echo '<div class="alert alert-info">';
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) { echo $message; }
    echo '</div>';
}
?>
</b>
<u><h1><?php echo $this->escapeHtml($title); ?></h1></u>
<p>Hier sehen Sie eine Liste aller Cash-Back-Aktionen.</p>
<p>Sie k&oumlnnen Eintr&aumlge l&oumlschen oder den Status einer Cash-Back-Aktion auf "1" setzen, um Sie zu best&aumltigen.</p>

<table class="table">
	<tr>
		<th>Multiplikator-ID</th>
		<th>Event-ID</th>
		<th>Anfang</th>
		<th>Ende</th>
		<th>Wert</th>
		<th>Status</th>
		<th></th>
		<th></th>
	</tr>
 <?php foreach ($cashbackmultiplikatoren as $cashbackmultiplikator): ?>
 <tr> 
        <td><?php echo $this->escapeHtml($cashbackmultiplikator->getId()); ?></td>
   	    <td><?php echo $this->escapeHtml($cashbackmultiplikator->getEventId()); ?></td>
    	<td><?php echo $this->escapeHtml($cashbackmultiplikator->getAnfang()); ?></td>
   	    <td><?php echo $this->escapeHtml($cashbackmultiplikator->getEnde()); ?></td>
   		<td><?php echo $this->escapeHtml($cashbackmultiplikator->getWert()); ?></td>
   	    <td><?php echo $this->escapeHtml($cashbackmultiplikator->getFreigegeben()); ?></td>
   	    <td><a href="<?php echo $this->url('cashbackmultiplikator', array('action' => 'delete', 'id' => $cashbackmultiplikator->getId()));?>">L&oumlschen</a></td>
   	    <td><a href="<?php echo $this->url('cashbackmultiplikator', array('action' => 'edit', 'id' => $cashbackmultiplikator->getId()));?>">Status &aumlndern</a></td>	
 <?php endforeach; ?>
 </table>