<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Multiplikator\Module'                        => __DIR__ . '/Module.php',
    'Multiplikator\Controller\MultiplikatorController' => __DIR__ . '/src/Multiplikator/Controller/MultiplikatorController.php',
    'VeranstaltungTest\Framework\TestCase'        => __DIR__ . '/tests/Veranstaltung/Framework/TestCase.php',
    'VeranstaltungTest\SampleTest'                => __DIR__ . '/tests/Veranstaltung/SampleTest.php',
);
