<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Pwvergessen\Module'                        => __DIR__ . '/Module.php',
    'Pwvergessen\Controller\PwvergessenController' => __DIR__ . '/src/Pwvergessen/Controller/PwvergessenController.php',
);
