<?php
use Zend\Filter\DateTimeFormatter;


?>
<h1><u>Liste aller Events</u></h1>
<p>*Leere Felder bedeuten dieser Wert wurde nicht in der Datenbank eingetragen</p>
<form action=mitarbeitereventansicht/search>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Event suchen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>
<table class="table" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0" >
	<tr>
	    <th>ID</th>
		<th>Veranstaltungsid</th>
		<th>Teilnehmerlimit</th>
		<th>Name</th>
		<th>Ort</th>
		<th>Vorgaengerid</th>
		<th>Geschlechtsbeschraenkung</th>
		<th>Meisterschaftsbeschraenkung</th>
		<th>Anmeldegebuehr</th>
		<th>Datum</th>
		<th>Postleitzahl</th>
		<th>Strasse</th>
		<th>Hausnummer</th>
		<th>Lizenz</th>
		<th>Altersminimum</th>
		<th>Altersmaximum</th>
		<th>Status</th>
	
		
		
	</tr>
 <?php foreach ($MitarbeiterAnsichtevent as $Mitarbeitereventansicht1): ?>
 <tr>
	        <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getId()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getVeranstaltungsid()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getTeilnehmerlimit()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getName()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getOrt()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getVorgaengerid()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getGeschlechtsbeschraenkung()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getMeisterschaftsbeschraenkung()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getAnmeldegebuehr()); ?>&#8364;</td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getDatum()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getPostleitzahl()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getStrasse()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getHausnummer()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getLizenz()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getAltersminimum()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getAltersmaximum()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeitereventansicht1->getStatus()); ?></td>
            
    		
         
			
 <?php endforeach; ?>
 
 </table>