<?php
use Zend\Filter\DateTimeFormatter;


?>
<h1><u>Liste aller Athleten</u></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<form action=mitarbeiteransichtathlet/search>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Athlet suchen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>
<table class="table"  cellpadding="5" cellspacing="0" bgcolor="#E0E0E0" >
	<tr>
	    <th>ID</th>
		<th>Name</th>
		<th>Vorname</th>
		<th>Titel</th>
		<th>Zusatz</th>
		<th>Geburtstag</th>
		<th>Geschlecht</th>
		<th>Telefonnummer1</th>
		<th>Telefonnummer2</th>
		<th>Telefonnummer3</th>
		<th>Fax</th>
		<th>Email</th>
		<th>Firma</th>
		<th>IBAN</th>
		<th>BIC</th>
		<th>Historie</th>
		<th>Umkreis</th>
		<th>Werbung</th>
		<th>Status</th>
		
		
	</tr>
 <?php foreach ($MitarbeiterAnsichtAthleten as $MitarbeiterAnsichtAthlet): ?>
 <tr>
	        <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getId()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getName()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getVorname()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getTitel()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getZusatz()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getGeburtstag()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getGeschlecht()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getTelefonnummer1()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getTelefonnummer2()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getTelefonnummer3()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getFax()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getEmail()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getFirma()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getIban()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getBic()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getHistorie()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getUmkreis()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getWerbung()); ?></td>
            <td><?php echo $this->escapeHtml($MitarbeiterAnsichtAthlet->getStatus()); ?></td>
    		
         
			
 <?php endforeach; ?>
 
 </table>