<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Vereinsadminaendern\Module'                        => __DIR__ . '/Module.php',
    'Vereinsadminaendern\Controller\VereinsadminaendernController' => __DIR__ . '/src/Vereinsadminaendern/Controller/VereinsadminaendernController.php',
    'VereinsadminaendernTest\Framework\TestCase'        => __DIR__ . '/tests/Vereinsadminaendern/Framework/TestCase.php',
    'VereinsadminaendernTest\SampleTest'                => __DIR__ . '/tests/Vereinsadminaendern/SampleTest.php',
);
