<?php
$title = 'Edit event';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$url = $this->url('event', array(
    'action' => 'rewrite',
    'id' => $id
));
$form->setAttribute('action', $url);
$form->get('submit')->setAttribute('value', 'rewrite');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('veranstaltungsid'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('postleitzahl'));
echo $this->formRow($form->get('ort'));
echo $this->formRow($form->get('strasse'));
echo $this->formRow($form->get('hausnummer'));
echo $this->formRow($form->get('vorgaengerid'));
echo $this->formRow($form->get('anmeldegebuehr'));
echo $this->formRow($form->get('datum'));
echo $this->formRow($form->get('geschlecht'));
echo $this->formRow($form->get('beschreibung'));
echo $this->formRow($form->get('sportart'));
echo $this->formRow($form->get('teilnehmerlimit'));
echo $this->formRow($form->get('kategorien'));
echo $this->formRow($form->get('altersminimum'));
echo $this->formRow($form->get('altersmaximum'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);