<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Profilansicht Event';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><img src="<?php echo $link;?>" width="100" height="25" /> 
(Durchschnitt: <?php echo $this->escapeHtml($avg); ?>)
<?php if($x == 1)
    {
    ?><?php echo "Abmelden"; 
    }
    if($x == 0) 
    {    
    ?><a href="<?php echo $this->url('ergebnis', array(
    'action' => 'anmelden', 'id' => $event->getId()));
    ?>">Anmelden</a><?php 
    }
    if($x == 2)
    {
        echo "Event wird oder wurde bereits durchgefuehrt";
    }?></p>
<p><?php if($vorgaenger)
    echo "Vorjahresbewertung: ";
    echo $this->escapeHtml($vorgaenger); ?></p>


<table class="table">
	<tr>
		<td>Name</td>
		<td><a href="<?php
                    echo $this->url('event', array(
                    'action' => 'edit',
                    'id' => $event->getId()));?>">
             <?php echo $this->escapeHtml($event->getName()); ?></a></td>
    </tr>
    <tr>         
		<td>Ort</td>
		<td><?php echo $this->escapeHtml($event->getOrt()); ?></td>
	</tr>	
	<tr>	
		<td>PLZ</td>
		<td><?php echo $this->escapeHtml($event->getPostleitzahl()); ?></td>
	</tr>
	<tr>
		<td>Strasse</td>
		<td><?php echo $this->escapeHtml($event->getStrasse()); ?></td>
	</tr>
	<tr>
		<td>Hausnummer</td>
		<td><?php echo $this->escapeHtml($event->getHausnummer()); ?></td>
	</tr>
	<tr>	
		<td>Datum</td>
		<td><?php echo $this->escapeHtml($event->getDatum()); ?></td>
	</tr>	
	<tr>
		<td>Meisterschaft</td>
		<td><?php echo $event->getMeisterschaftsbeschraenkung() ? $event->getMeisterschaftsbeschraenkung() : 'No'; ?></td>
	</tr>	
	<tr>
		<td>Geschlecht</td>
		<td><?php echo $event->getGeschlechtsbeschraenkung() ? $event->getGeschlechtsbeschraenkung() : 'No'; ?></td>
	</tr>
	<tr>	
		<td>Gebuehr</td>
		<td><?php echo $this->escapeHtml($event->getAnmeldegebuehr()); ?> &#8364;</td>
	</tr>
	<tr>	
		<td>Sportart</td>
		<td><?php echo $this->escapeHtml($event->getSportart()->getBezeichnung()?$event->getSportart()->getBezeichnung(): 'Keine Angaben'); ?></td>	
	</tr>
    <tr>
		<td><a
			href="<?php
    
echo $this->url('ergebnis', array(
        'action' => 'ergebnis',
        'id' => $event->getId()
    ));
    ?>">Ergebnisliste einsehen</a>
		</td>
		<td></td>
	</tr>
 </table>
 
 <a
			href="<?php
    
echo $this->url('veranstaltung', array(
        'action' => 'profil',
        'id' => $event->getVeranstaltungsid()
    ));
    ?>">Zur Veranstaltung</a>