<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Vereinsadmin &aumlndern';
$this->headTitle($title);
?>
<h1><u>Liste aller Vereine(Status=0)</u></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>

<form action=vereinsadminaendern/search>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Verein suchen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
    
  </table>
</form>




<table class="table"  cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
	<tr>
	
		<th>Adminemail</th>
		<th>VereinsID</th>
		<th>Admin &auml;ndern</th>
		
		
	</tr>
 <?php foreach ($vereinsadminaendern1 as $vereinsadminaendern): ?>
 <tr>
		
            <td><?php echo $this->escapeHtml($vereinsadminaendern->getAdminemail()); ?></td>
    		<td><?php echo $this->escapeHtml($vereinsadminaendern->getId()); ?></td>
    		<td><a href="<?php  
                 echo $this->url('vereinsadminaendern', array(
                     'action' => 'update',
                        'id' => $vereinsadminaendern->getId()
                   ));
                 ?>">
             <img src="img/edit.png" width="30" height="30" ></a></td>
			
 <?php endforeach; ?>
 </table>