<?php
$title = 'Neuen Vereinsadmin anlegen oder editieren';
$this->headTitle($title);
?>
<h1><u>Neuen Vereinsadmin anlegen oder editieren</u></h1>
<br>
<p>
	<a
		href="<?php

echo $this->url('vereinsadminaendern', array(
    'action' => 'index'
));
?>">Zur&uumlck zur &Uumlbersicht</a>
</p>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<form>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    <tr>
      <td align="right">VereinsID:</td>
      <td><input name="vereinid" value=<?php echo $id; ?> type="text" size="30" maxlength="30" readonly></td>
    </tr>
    <tr>
      <td align="right">Adminemail:</td>
      <td><input name="adminemail" type="Email" size="30" maxlength="30"></td>
    </tr>
     <tr>
      <td align="right">Passwort:</td>
      <td><input name="passwort" type="text" size="30" maxlength="30"></td>
      <td>*Passwort muss zwischen 8 und 16 Zeichen lang sein</td>
    </tr>
      <td align="right"></td>
      <td>
        <input type="submit" value=" Absenden" name="absenden"class="button">
     
    </tr>
  </table>
</form>

