
 <?php
 
 $title = 'Athleten suchen';
 $this->headTitle($title);
 ?>
  <h1><?php echo $this->escapeHtml($title); ?></h1>
  <?php
  $form->setAttribute('action', $this->url('suche', array('action' => 'searchathlet')));
  $form->prepare();
 
  echo $this->form()->openTag($form);
  echo $this->formRow($form->get('Vorname'));
  echo $this->formRow($form->get('Name'));
  echo $this->formSubmit($form->get('submit'));
  echo $this->form()->closeTag();
  