 <?php
 // module/Gutscheincode/view/Gutscheincode/Gutscheincode/index.phtml:
 //TODO AUSGABE FUNKTIONIERT NOCH NICHT

 $title = 'Athlet';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>


 <table class="table">
 <tr>
     <th>ID</th>
     <th>Vorname</th>
     <th>Name</th>
     <th>E-Mail</th>
     <th>Telefonnummer</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($athleten as $athlet) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($athlet->id);?></td>
     <td><?php echo $this->escapeHtml($athlet->vorname);?></td>
     <td><?php echo $this->escapeHtml($athlet->name);?></td>   
     <td><?php echo $this->escapeHtml($athlet->email);?></td>
     <td><?php echo $this->escapeHtml($athlet->telefonnummer);?></td>

     
 </tr>
 <?php endforeach; ?>
 </table>