<?php
use Zend\Filter\DateTimeFormatter;
$title = 'My Veranstaltungs List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a
		href="<?php

echo $this->url('veranstaltung', array(
    'action' => 'add'
));
?>">Add new item</a>
</p>

<table class="table">
	<tr>
		<th>Name:</th>
	</tr>
 <?php foreach ($veranstaltungen as $veranstaltung): ?>
 <tr>
		<td><a
			href="<?php
    
echo $this->url('veranstaltung', array(
        'action' => 'show',
        'id' => $veranstaltung->getId()
    ));
    ?>">
             <?php echo $this->escapeHtml($veranstaltung->getName()); ?></a></td>
	<td><a href="<?php  
                 echo $this->url('veranstaltung', array(
                     'action' => 'hist',
                        'id' => $veranstaltung->getId()
                   ));
                 ?>">
             History</a></td>		
 <?php endforeach; ?>
 </table>