<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Veranstalterverifizieren\Module'                        => __DIR__ . '/Module.php',
    'Veranstalterverifizieren\Controller\VeranstalterverifizierenController' => __DIR__ . '/src/Veranstalterverifizieren/Controller/VeranstalterverifizierenController.php',
);
