<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
 'Mitarbeiteransichtathlet\Module'                        => __DIR__ . '/Module.php',
    'Mitarbeiteransichtathlet\Controller\MitarbeiteransichtathletController' => __DIR__ . '/src/Mitarbeiteransichtathlet/Controller/MitarbeiteransichtathletController.php',
    'MitarbeiteransichtathletTest\Framework\TestCase'        => __DIR__ . '/tests/Mitarbeiteransichtathlet/Framework/TestCase.php',
    'MitarbeiteransichtathletTest\SampleTest'                => __DIR__ . '/tests/Mitarbeiteransichtathlet/SampleTest.php',
);
