<?php
$title = 'Bewertung abgeben:';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('bewertung', array(
    'action' => 'add', 'id' => $eventid
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('eventid'));
echo $this->formHidden($form->get('athletid'));
echo $this->formRow($form->get('text'));
echo $this->formRow($form->get('likert'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>
<p>
	<a
		href="<?php

echo $this->url('login');
?>">Uebersicht</a>
</p>