<?php
$title = 'Bewertungen zum ausgewaehlten Event';
$text = 'Durchschnittliche Bewertung und Name des Events';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $this->escapeHtml($text); ?></p>
<p>Name: <?php echo $this->escapeHtml($event->getName()); ?></p>
<p>Durchschnitt: <?php echo $this->escapeHtml($avg); ?></p>
<p><?php if($vorgaenger)
    echo "Vorjahresbewertung: ";
    echo $this->escapeHtml($vorgaenger); ?></p>
    
<p><?php if($past)
    echo "Durchschnittswert anhand aller vergangenen Vorgaenger: ";
    echo $this->escapeHtml($past); ?></p>    

 <?php foreach ($bewertungen as $bewertung): ?>
  <div style="width: 300px; float:left; margin-right:80px; border: 3px solid #E6E6E6; padding:5px;"><tr>
 <?php error_reporting(0);
 $x = $athlet->getAthlet($bewertung->getAthletid());
 error_reporting(E_ALL);?>
 <td><?php echo $this->escapeHtml($x->Name);?> <?php  echo $this->escapeHtml($x->Vorname);?></td>
  <td>
  <img src="img/<?= $star->createLink3($bewertung->getLikert())?>" width="100" height="50" />
  </td><br /><hr />
  <td><?php echo $this->escapeHtml($bewertung->getText()); ?></td>			
 </div>
 <?php endforeach; ?>
  </table><br />
 
 
 
 <a
		href="<?php

echo $this->url('bewertung', array(
    'action' => 'index'
));
?>">