<?php
use Zend\Filter\DateTimeFormatter;
$title = 'My veranstalter list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a
		href="<?php

echo $this->url('veranstalter', array(
    'action' => 'add'
));
?>">Add new item</a>
</p>


<table class="table">
	<tr>
		<th>Name</th>
		<th>Vorname</th>
		<th>Email</th>
		<th>Verifizierung</th>
		<th>Firmenname</th>
		<th>Postleitzahl</th>
		<th>Ort</th>
        <th>Löschen</th>
        <th>Profil</th>
		<th>&nbsp;</th>
		<th></th>
	</tr>
 <?php foreach ($veranstaltern as $veranstalter): ?>
 <tr>
		<td><a
			href="<?php
    
echo $this->url('veranstalter', array(
        'action' => 'edit',
        'id' => $veranstalter->getId()
    ));
    ?>">
             <?php echo $this->escapeHtml($veranstalter->getName()); ?></a></td>
            <td><?php echo $this->escapeHtml($veranstalter->getVorname()); ?></td>
    		<td><?php echo $this->escapeHtml($veranstalter->getEmail()); ?></td>
    		<td><?php echo $this->escapeHtml($veranstalter->getVerifiziert()); ?></td>
    		<td><?php echo $this->escapeHtml($veranstalter->getFirmenname()); ?></td>
    		<td><?php echo $this->escapeHtml($veranstalter->getPostleitzahl()); ?></td>
    		<td><?php echo $this->escapeHtml($veranstalter->getOrt()); ?></td>
            <td><a href="<?php  
                 echo $this->url('veranstalter', array(
                     'action' => 'delete',
                        'id' => $veranstalter->getId()
                   ));
                 ?>">
             <img src="img/delete.png" width="30" height="30" alt="delete"></a></a></td>
			
            
                      
             			<td><a href="<?php  
                 echo $this->url('veranstalter', array(
                     'action' => 'profil',
                        'id' => $veranstalter->getId()
                   ));
                 ?>">
             <img src="img/profil.png" width="30" height="30" alt="profil"></a></a></td>
            
            
			<td><a href="<?php  
                 echo $this->url('veranstalter', array(
                     'action' => 'show',
                        'id' => $veranstalter->getId()
                   ));
                 ?>">
             Veranstaltung</a></td>
             
			
 <?php endforeach; ?>
 </table>