<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Veranstalterbezahlung\Module'                        => __DIR__ . '/Module.php',
    'Veranstalterbezahlung\Controller\VeranstalterbezahlungController' => __DIR__ . '/src/Veranstalterbezahlung/Controller/VeranstalterbezahlungController.php',
    'VeranstalterbezahlungTest\Framework\TestCase'        => __DIR__ . '/tests/Veranstalterbezahlung/Framework/TestCase.php',
    'VeranstalterbezahlungTest\SampleTest'                => __DIR__ . '/tests/Veranstalterbezahlung/SampleTest.php',
);
