<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Athleteinsicht\Module'                        => __DIR__ . '/Module.php',
    'Athleteinsicht\Controller\AthleteinsichtController' => __DIR__ . '/src/Athleteinsicht/Controller/AthleteinsichtController.php',
    'AthleteinsichtTest\Framework\TestCase'        => __DIR__ . '/tests/Athleteinsicht/Framework/TestCase.php',
    'AthleteinsichtTest\SampleTest'                => __DIR__ . '/tests/Athleteinsicht/SampleTest.php',
);
