<?php
$title = 'Werbeauftrag suchen';
$this->headTitle($title);
?>
<h1><u>Veranstalter suchen</u></h1>


<p>
	<a
		href="<?php

echo $this->url('mitarbeiteransichtveranstalter', array(
    'action' => 'index'
));
?>">Zur&uumlck zur &Uumlbersicht</a>
</p>
<form action="search">
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    <tr>
      <td align="right">ID:</td>
      <td><input name="id" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">Email:</td>
      <td><input name="email" type="text" size="30" maxlength="30"></td>
    </tr>
      <td align="right">Formular:</td>
      <td>
        <input type="submit" value=" Absenden" name="absenden" class="button">
     
    </tr>
  </table>
</form>

<table class="table" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0" >
	<tr>
	    <th>ID</th>
		<th>Name</th>
		<th>Vorname</th>
		<th>Email</th>
		<th>IBAN</th>
		<th>BIC</th>
		<th>Verifiziert</th>
		<th>Firmenname</th>
		<th>Strasse</th>
		<th>Hausnummer</th>
		<th>Postleitzahl</th>
		<th>Ort</th>
		
	
		
		
	</tr>
	
	
 <?php if($Mitarbeiteransichtveranstalter1!=NULL){
     
 
 
 
 foreach ($Mitarbeiteransichtveranstalter1 as $Mitarbeiteransichtveranstalter): ?>
 <tr>
	        <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getId()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getName()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getVorname()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getEmail()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getIban()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getBic()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getVerifiziert()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getFirmenname()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getStrasse()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getHausnummer()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getPostleitzahl()); ?></td>
            <td><?php echo $this->escapeHtml($Mitarbeiteransichtveranstalter->getOrt()); ?></td>
         
            
    		
         
			
 <?php endforeach;

 
 }?>
 
 </table>