<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Athletenbezahlung\Module'                        => __DIR__ . '/Module.php',
    'Athletenbezahlung\Controller\AthletenbezahlungController' => __DIR__ . '/src/Athletenbezahlung/Controller/AthletenbezahlungController.php',
    'AthletenbezahlungTest\Framework\TestCase'        => __DIR__ . '/tests/Athletenbezahlung/Framework/TestCase.php',
    'AthletenbezahlungTest\SampleTest'                => __DIR__ . '/tests/Athletenbezahlung/SampleTest.php',
);
