<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Veranstaltung\Module'                        => __DIR__ . '/Module.php',
    'Veranstaltung\Controller\VeranstaltungController' => __DIR__ . '/src/Veranstaltung/Controller/VeranstaltungController.php',
    'VeranstaltungTest\Framework\TestCase'        => __DIR__ . '/tests/Veranstaltung/Framework/TestCase.php',
    'VeranstaltungTest\SampleTest'                => __DIR__ . '/tests/Veranstaltung/SampleTest.php',
);
