<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Lizenz\Module'                        => __DIR__ . '/Module.php',
    'Lizenz\Controller\LizenzController' => __DIR__ . '/src/Lizenz/Controller/LizenzController.php',
);
