<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Veranstalter\Module'                        => __DIR__ . '/Module.php',
    'Veranstalter\Controller\VeranstalterController' => __DIR__ . '/src/Veranstalter/Controller/VeranstalterController.php',
    'VeranstaltungTest\Framework\TestCase'        => __DIR__ . '/tests/Veranstaltung/Framework/TestCase.php',
    'VeranstaltungTest\SampleTest'                => __DIR__ . '/tests/Veranstaltung/SampleTest.php',
);
