<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
 'Mitarbeiteransichtveranstalter\Module'                        => __DIR__ . '/Module.php',
    'Mitarbeiteransichtveranstalter\Controller\MMitarbeiteransichtveranstalterController' => __DIR__ . '/src/Mitarbeiteransichtveranstalter/Controller/MitarbeiteransichtveranstalterController.php',
    'MitarbeiteransichtveranstalterTest\Framework\TestCase'        => __DIR__ . '/tests/Mitarbeiteransichtveranstalter/Framework/TestCase.php',
    'MitarbeiteransichtveranstalterTest\SampleTest'                => __DIR__ . '/tests/Mitarbeiteransichtveranstalter/SampleTest.php',
);
