<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
//     'Bild\Module'                        => __DIR__ . '/Module.php',
//     'Bild\Controller\BildController' => __DIR__ . '/src/Bild/Controller/BildController.php',
    'VeranstaltungTest\Framework\TestCase'        => __DIR__ . '/tests/Veranstaltung/Framework/TestCase.php',
    'VeranstaltungTest\SampleTest'                => __DIR__ . '/tests/Veranstaltung/SampleTest.php',
);
