<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Labeleventzuordnung\Module'                        => __DIR__ . '/Module.php',
    'Labeleventzuordnung\Controller\LabeleventzuordnungController' => __DIR__ . '/src/Labeleventzuordnung/Controller/LabeleventzuordnungController.php',
);
