<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Vereineinsicht\Module'                        => __DIR__ . '/Module.php',
    'Vereineinsicht\Controller\VereineinsichtController' => __DIR__ . '/src/Vereineinsicht/Controller/VereineinsichtController.php',
    'VereineinsichtTest\Framework\TestCase'        => __DIR__ . '/tests/Vereineinsicht/Framework/TestCase.php',
    'VereineinsichtTest\SampleTest'                => __DIR__ . '/tests/Vereineinsicht/SampleTest.php',
);
