 <?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Gutscheincode einloesen';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('gutscheincode', array('action' => 'einloesen')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('id'));
 echo $this->formRow($form->get('athletenid'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 