<?php
$title = 'Werbeauftrag anlegen';
$this->headTitle($title);
?>
<h1>
	<u>Werbeauftrag anlegen</u>
</h1>

<?php

if ($this->flashMessenger()->hasMessages()) {
    
    echo '<div class="alert alert-info">';
    
    $messages = $this->flashMessenger()->getMessages();
    foreach ($messages as $message) {
        echo $message;
    }
    
    echo '</div>';
}

?>




<p>
	<a
		href="<?php

echo $this->url('werbeauftrag', array(
    'action' => 'index'
));
?>">Zur&uumlck zur &Uumlbersicht</a>
</p>









<?php
$form = $this->form;
$form->setAttribute('action', $this->url('werbeauftrag', array(
    'action' => 'add',
    'name' => 'name'
)));
$form->get('submit')->setAttribute('value', 'Anlegen');
$form->prepare();

echo $this->form()->openTag($form);
// echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('name'));

?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>
