<?php
use Zend\Filter\DateTimeFormatter;


?>
<h1><u>Liste aller Werbeauftr&aumlge</u></h1>

<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>



<form action=werbeauftrag/add>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value=" Neuen Werbeauftrag anlegen " style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<form action=werbeauftrag/search>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Nach bestimmten Auftrag suchen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<form action=werbeauftrag/werbeauftragveranstalterzuordnung>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Werbeauftrag einem Veranstalter zuweisen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<form action=werbeauftrag/werbeauftragathletenzuordnung>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">

    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Werbeauftrag einem Athleten zuweisen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>


<table class="table" border="0" cellpadding="5" cellspacing="0" >
	<tr >
	    <th>ID</th>
		<th>Name</th>
		<th>Editieren</th>
		<th>L&oumlschen</th>
		<th>Zuordnung:Werbeauftrag-Athlet-Veranstalter</th>
		
	</tr>
 <?php foreach ($werbeauftrage as $werbeauftrag): ?>
 <tr>
	        <td><?php echo $this->escapeHtml($werbeauftrag->getId()); ?></td>
            <td><?php echo $this->escapeHtml($werbeauftrag->getName()); ?></td>
            

              <td><a href="<?php  
                 echo $this->url('werbeauftrag', array(
                     'action' => 'edit',
                        'id' => $werbeauftrag->getId()
                   ));
                 ?>">
             <img src="img/edit.png" width="30" height="30" ></a></td>
             
             <td><a href="<?php  
                 echo $this->url('werbeauftrag', array(
                     'action' => 'delete',
                        'id' => $werbeauftrag->getId()
                   ));
                 ?>">
             <img src="img/delete.png" width="30" height="30" ></a></td>
             
           <td><a href="<?php  
                 echo $this->url('werbeauftrag', array(
                     'action' => 'zuordnung',
                        'id' => $werbeauftrag->getId()
                   ));
                 ?>"><img src="img/list.png" width="30" height="30" >
                 
             </a></td>
    		
         
			
 <?php endforeach; ?>
 </table>