<?php
$title = 'Werbeauftrag einem Veranstalter zuweisen';
$this->headTitle($title);
?>
<h1><u>Werbeauftrag einem Veranstalter zuweisen</u></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>

<p>
	<a
		href="<?php

echo $this->url('werbeauftrag', array(
    'action' => 'index'
));
?>">Zur&uumlck zur &Uumlbersicht</a>
</p>
<form action="werbeauftragveranstalterzuordnung">
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    <tr>
      <td align="right">WerbeauftragID:</td>
      <td><input name="werbeauftragid" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">VeranstalterID:</td>
      <td><input name="veranstalterid" type="text" size="30" maxlength="30"></td>
    </tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Zuweisen" name="absenden" class="button">
    </tr>
  </table>
</form>
