<img src="../../img/3path.png" width="720" height="136" alt="3path" style="margin-left: 200px; margin-top: 30px"></a>
<?php
$title = '';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('strecke', array(
    'action' => 'add',
    'id' => $id
)));
$form->get('submit')->setAttribute('value', 'Strecke festlegen');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('id'));
echo $this->formHidden($form->get('eventid'));

?>

<div class="searchtitle">Streckenlänge:</div>
<?php
echo $this->formRow($form->get('streckenlaenge'));
?> km
<div class="clear"></div>
<?php




// echo $this->formRow($form->get('bildname'));
?>
<div style="margin-top: 25px;margin-bottom: 25px;">
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>
<p>
</p>