<?php
$title = 'Edit veranstalter';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$url = $this->url('veranstalter', array(
    'action' => 'edit',
    'id' => $id
));
$form->setAttribute('action', $url);
$form->get('submit')->setAttribute('value', 'Edit');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('vorname'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('passwort'));
echo $this->formRow($form->get('iban'));
echo $this->formRow($form->get('bic'));
echo $this->formRow($form->get('verifiziert'));
echo $this->formRow($form->get('firmenname'));
echo $this->formRow($form->get('strasse'));
echo $this->formRow($form->get('hausnummer'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);