<?php
use Zend\Filter\DateTimeFormatter;
$title = 'My Strecke list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
	<tr>
		<th>ID</th>
		<th>Event-ID</th>
		<th>Strecke in km</th>
		<th>&nbsp;</th>
		<th></th>
	</tr>
 <?php foreach ($strecken as $strecke): ?>
 <tr>
		    <td><?php echo $this->escapeHtml($strecke->getId()); ?></td>
            <td><?php echo $this->escapeHtml($strecke->getEventid()); ?></td>
            <td><?php echo $this->escapeHtml($strecke->getStreckenlaenge()); ?></td>
 <?php endforeach; ?>
 </table>