<?php
$title = 'Neuen Mitarbeiter anlegen';
$this->headTitle($title);
?>
<h1><u>Neuen Verein anlegen</u></h1>

<p>
	<a
		href="<?php

echo $this->url('vereineinsicht', array(
    'action' => 'index'
));
?>">&Uumlbersicht</a>
</p>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<form action="add">
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    <tr>
      <td align="right">ID:</td>
      <td><input name="id" type="text" size="30" maxlength="30"></td>
    </tr>
    
    <tr>
      <td align="right">Name:</td>
      <td><input name="name" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">Adminemail:</td>
      <td><input name="adminemail" type="text" size="30" maxlength="30"></td>
       <td align="right">Passwort:</td>
      <td><input name="passwort" type="text" size="30" maxlength="30"></td>
      <td align="right"> * Passwort: min. 6 max. 16 Zeichen</td>
    </tr>
    <tr>
      <td align="right">IBAN:</td>
      <td><input name="iban" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">BIC:</td>
      <td><input name="bic" type="text" size="30" maxlength="30"></td>
    </tr>
    
    <tr>
      <td align="right">Email:</td>
      <td><input name="email" type="text" size="30" maxlength="30"></td>
    </tr>
   
    <tr>
      <td align="right">Strasse:</td>
      <td><input name="strasse" type="text" size="30" maxlength="30"></td>
    </tr>

    <tr>
      <td align="right">Hausnummer:</td>
      <td><input name="hausnummer" type="text" size="30" maxlength="30"></td>
    </tr>
  
     <tr>
      <td align="right">PLZ:</td>
      <td><input name="plz" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">Ort:</td>
      <td><input name="ort" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      
      
      <td align="right"> Status:
    <select name="status" size="2">
      <option>1</option>
      <option>0</option>
     
    </select>
    </td>
    </tr>
    <tr>
      <td align="right">Kontoinhaber:</td>
      <td><input name="kontoinhaber" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">Vereinsvertreter:</td>
      <td><input name="vereinsvertreter" type="text" size="30" maxlength="30"></td>
    </tr>
    
    


    </tr>
      <td align="right"></td>
      <td>
        <input type="submit" value=" Absenden" name="absenden" class="button">
     
    </tr>
  </table>
</form>
