<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Vereine bearbeiten';
$this->headTitle($title);
?>
<h1><u>Vereine bearbeiten</u></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<form action=verein/registrieren>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0"  >
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Neuen Verein anlegen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<table class="table">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Adminemail</th>
		<th>IBAN</th>
		<th>BIC</th>
		<th>Email</th>
		<th>Strasse</th>
        <th>Hausnummer</th>
        <th>PLZ</th>
        <th>Ort</th>
        <th>Status</th>
        <th>Bankkontoinhaber</th>
         <th>Vereinsvertreter</th>
		<th>Editieren</th>
		<th>L&ouml;schen</th>
		<th></th>
		
	</tr>
	
 <?php foreach ($vereine as $verein): ?>
 <tr>
		
            
             <td><?php echo $this->escapeHtml($verein->getId()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getName()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getAdminemail()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getIban()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getBic()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getEmail()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getStrasse()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getHausnummer()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getPostleitzahl()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getOrt()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getStatus()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getBankkontoinhaber()); ?></td>
            <td><?php echo $this->escapeHtml($verein->getVereinsvertreter()); ?></td>
               
            <td><a href="<?php  
                 echo $this->url('vereineinsicht', array(
                     'action' => 'edit',
                        'id' => $verein->getId()
                   ));
                 ?>">
             <img src="img/edit.png" width="30" height="30" alt="delete"></a></td>
             
              <td><a href="<?php  
                 echo $this->url('vereineinsicht', array(
                     'action' => 'delete',
                        'id' => $verein->getId()
                   ));
                 ?>">
             <img src="img/delete.png" width="30" height="30" alt="delete"></a></td>
            
			
 <?php endforeach; ?>
 </table>