<?php
$title = 'Add new Admin';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array(
    'action' => 'add'
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('vorname'));
echo $this->formRow($form->get('nachname'));


?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>
<p>
	<a
		href="<?php

echo $this->url('admin', array(
    'action' => 'index'
));
?>">Uebersicht</a>
</p>