<h1>Hilfe - FAQs</h1>
<br/>
<h2>Hilfe zu Athlet und Verein</h2><hr/>
<h4>Was mache ich, wenn ich mich als Athleten registrieren will?</h4>
Wählen sie bitte „Athlet registrieren“ und geben sie bitte alle für die Athleten-Registrierung erforderlichen Daten ein.<br/><br/><br/><br/>
<h4>Was mache ich, wenn ich mich als Verein registrieren will?</h4>
Wählen sie bitte „Verein registrieren“ und geben sie bitte alle für die Vereins-Registrierung erforderlichen Daten ein.<br/><br/><br/><br/>
<h4>Ich möchte die Registrierung als Athlet / Verein abbrechen, wie geht das?</h4>
Bitte drücken sie vor abschließen den Home-Button in der Navigationsleiste oder wählen klicken sie den Zurücksetzen-Button im Registrierungsprozess.<br/><br/><br/><br/>
<h4>Ich habe mich vor Abschluss der Registrierung vertippt und möchte ein Feld ändern, was mache ich?</h4>
Bitte wählen sie das entsprechende Formular und ändern ihre Angabe.<br/><br/><br/><br/>
<h4>Ich habe mich vor Abschluss der Registrierung eines Athleten / Vereins mehrfach bei der Eingabe vertippt und möchte von vorne beginnen, wie gehe ich vor?</h4>
Bitte klicken sie auf den Zurücksetzen-Button. Ihnen wird dann ein neues Registrierungsformular angezeigt.<br/><br/><br/><br/>
<h4>Ich kann die Registrierung nicht abschließen, woran liegt das?</h4>
Bitte überprüfen sie, ob alle erforderlichen Felder ausgefüllt sind. Angaben sind für eine erfolgreiche Registrierung notwendig.<br/><br/><br/><br/>
<h4>Warum muss ich bei der Registrierung als Athlet mein Passwort doppelt angeben?</h4>
So werden Tippfehler im Passwort vermieden und ist für ein korrektes Login-Passwort förderlich.<br/><br/><br/><br/>
<h4>Warum wird bei der Registrierung mein gewähltes Passwort mit „Sternchen“ dargestellt?</h4>
So wird ihre Privatsphäre gewährleistet und dient ihrer persönlichen Sicherheit.<br/><br/><br/><br/>
<h4>Ich möchte mir nach Abschluss der Registrierung meine angegebenen Daten anzeigen lassen, wo sehe ich meine Angaben?</h4>
Bitte gehen sie auf ihre Profilübersicht. Falls sie nicht eingeloggt sind, müssen sie sich vorher einloggen.<br/><br/><br/><br/>
<h4>Ich möchte nach Abschluss der Registrierung meine angegebenen Daten ändern, wie geht das?</h4>
Sie können ihre Angaben, die sie bei der Registrierung getätigt haben, in ihrem Profil über einen Button „ändern“ anpassen. Bitten stellen sie sicher, dass sie im entsprechenden Profil eingeloggt sind. <br/><br/><br/><br/>
<h4>Wo kann ich mich als Athlet für Veranstaltungen anmelden?</h4>
In ihrem Athleten-Profil.<br/><br/><br/><br/>

<h2>Hilfe zu Veranstalter</h2><hr/>
<h4>Wie kann ich die von mir bereits erstellten Veranstaltungen/ Events anzeigen lassen? </h4>
Klicken sie im Hauptmenü in der Kopfzeile auf den Reiter „Veranstaltung“ bzw. „Event“.<br/><br/><br/><br/>
<h4>Wie kann ich eine neue Veranstaltung erstellen? </h4>
Klicken sie im Hauptmenü in der Kopfzeile auf den Reiter „Veranstaltung“ und anschließend auf den Link „neue Veranstaltung hinzufügen“. <br/><br/><br/><br/>
<h4>Ich habe im vergangenen Jahr bereits eine ähnliche Veranstaltung angelegt. Kann ich diese als Vorlage verwenden? </h4>
Im ersten Schritt der Veranstaltungserstellung können sie unter „Vorlage auswählen?“ eine bereits von ihnen erstellte Veranstaltung als Vorlage auswählen. Sie müssen dann nur noch die Daten aktualisieren. <br/><br/><br/><br/>
<h4>Ich habe eine Veranstaltung erstellt. Wie kann ich Events dazu anlegen? </h4>
Legt man eine Veranstaltung an, wird man im nächsten Schritt automatisch zur Event-erstellen-Funktion weitergeleitet. 
Manuell kann man Events auch unter „Veranstaltung““→ „Veranstaltungsname“ → „neues Event hinzufügen“ anlegen. 
<br/><br/><br/><br/>
<h4>Ich habe einer Veranstaltung mit Events angelegt aber irrtümlicherweise falsche Daten eingegeben/ Daten vergessen. Kann ich das noch ändern? </h4>
Solange die Veranstaltung nicht öffentlich ist kann sie die Community nicht sehen oder sich anmelden. In diesem Zeitraum können Änderungen vorgenommen werden. 
Wird die Veranstaltung öffentlich geschaltet, können relevante Daten nur noch vom Betreiber auf Nachfrage geändert werden. 
<br/><br/><br/><br/>
<h4>Wie kann ich eine Veranstaltung öffentlich machen? </h4>
Klicken sie im Hauptmenü in der Kopfzeile auf „Veranstaltung“ Bei noch nicht öffentlichen Veranstaltungen ist der Link „go public“ verfügbar. <br/><br/><br/><br/>
<h4>Kann ich Veranstaltungen nachträglich löschen? </h4>
Nein. Wenden sie sich in diesem Fall bitte an den Betreiber. <br/><br/><br/><br/>
<h4>Kann ich die Bewertungen meiner Events einsehen? </h4>
Ja. Klicken sie in der Veranstaltungsübersicht auf den Button „Profil“. Sie sehen, falls Bewertungen abgegeben wurden die Durchschnittsbewertung, sowie die letzten drei Bewertungen mit Text.<br/><br/><br/><br/>

<h2>Hilfe zu Shop</h2><hr/>
<h4>Ich habe meine Bestellung irrtümlich aufgegeben, kann diese storniert werden? </h4>
Für Stornierungsanfragen kontaktieren sie bitte den Betreiber unter: admin@starmina.de<br/><br/><br/><br/>
<h4>Ich habe meine Artikelauswahl abgeschlossen, wie kann ich bestellen? </h4>
Klicken sie auf den Button „Warenkorb ansehen“ und anschließend auf „diesen Artikel verbindlich bestellen?“. Bei erfolgreicher Bestellung werden sie in ihre Bestellübersicht weitergeleitet. <br/><br/><br/><br/>
<h4>Wie errechnet sich der genaue Preis der Artikel? </h4>
Um Mengenrabatte zu realisieren, sammelt der Betreiber mithilfe des Shops Bestellungen und tätigt diese dann gesammelt in angemessenen Zeiträumen. 
Bei den Preisen im Shop handelt es sich um sogenannte „Maximalpreise“, also denjenigen Preis den der Betreiber an sie weitergeben müsste, sollte nur ein Artikel bestellt werden. In der Regel wird dieser sinken. 
<br/><br/><br/><br/>



