<?php
$title = 'Hier koennen Sie eine neue Label-Event-Zuordnung hinzufuegen:';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('labeleventzuordnung', array('action' => 'add')));
$form->get('submit')->setAttribute('value', 'Speichern');
$form->prepare();

//Anzeigen der Felder
echo $this->form()->openTag($form);
echo $this->formRow($form->get('eventid'));?><br><?php
echo $this->formRow($form->get('labelid'));?><br><?php
echo $this->formRow($form->get('status'));
?>
<br>
<br>
<!--Ausgabe des Buttons-->
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>
<br>
<p>
	<a href="<?php echo $this->url('labeleventzuordnung', array('action' => 'index'));?>
">Zur&uumlck zur &Uumlbersicht</a>
</p>