<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Hilfe\Module'                        => __DIR__ . '/Module.php',
    'Hilfe\Controller\HilfeController' => __DIR__ . '/src/Hilfe/Controller/HilfeController.php',
);
