<?php
$title = 'Neuen Betreiber anlegen';
$this->headTitle($title);
?>
<h1><u>Neuen Betreiber anlegen</u></h1>
<p>
	<a
		href="<?php

echo $this->url('betreiber', array(
    'action' => 'index'
));
?>">Zur&uumlck zur &Uuml;bersicht</a>
</p>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<form action="add">
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    <tr>
      <td align="right">ID:</td>
      <td><input name="id" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">Email:</td>
      <td><input name="email" type="Email" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">Passwort:</td>
      <td><input name="passwort" type="text" size="30" maxlength="30"></td>
      <td>*Passwort muss 8 bis 16 Zeichen lang sein</td>
    </tr>
    
    <tr>
      <td align="right">Name:</td>
      <td><input name="name" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">Vorname:</td>
      <td><input name="vorname" type="text" size="30" maxlength="30"></td>
    </tr>
    
    <tr>
    <td align="right">Rolle:</td>
      
 <td>
    <select name="rolle" size="2">
      <option>MA</option>
      <option>AD</option>
     
    </select>
    </td>


    </tr>
      <td align="right"></td>
      <td>
        <input type="submit" value=" Absenden" name="absenden" class="button">
     
    </tr>
  </table>
</form>
