<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Liste aller Mitarbeiter & Administratoren';
$this->headTitle($title);
?>
<h1><u>Liste aller Administratoren und Mitarbeiter</u></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<form action=betreiber/add>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0"  >
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value=" Neuen Betreiber anlegen " style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<form action=betreiber/search>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Nach bestimmten Betreiber suchen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
    <tr>
     <td align="right"></td>
      <td>
       * Hinweis: Rollen MA=Mitarbeiter           AD=Admin
        
      </td>
    </tr>
  </table>
</form>



<table class="table">
	   <tr>
		<th>Email</th>
		<th>Vorname</th>
		<th>Nachname</th>
		<th>Rolle</th>
		<th>Editieren</th>
		<th>L&ouml;schen</th>
		<th></th>
	   </tr>
	   
	   
 <?php foreach ($betreiberliste as $betreiber): ?>
    <tr>
		
             <td>
             <?php echo $this->escapeHtml($betreiber->getEmail()); ?></a></td>
            
              <td><?php echo $this->escapeHtml($betreiber->getVorname()); ?></td>
            <td><?php echo $this->escapeHtml($betreiber->getName()); ?></td>
             <td><?php echo $this->escapeHtml($betreiber->getRolle()); ?></td>
             
              
              
             <td><a href="<?php  
                 echo $this->url('betreiber', array(
                     'action' => 'edit',
                        'email' => $betreiber->getEmail()
                   ));
                 ?>">
             <img src="img/edit.png" width="30" height="30" alt="delete"></a></td>  
			
             <td><a href="<?php  
                 echo $this->url('betreiber', array(
                     'action' => 'delete',
                        'email' => $betreiber->getEmail()
                   ));
                 ?>">
             <img src="img/delete.png" width="30" height="30" alt="delete"></a></td>  
			
 <?php endforeach; ?>
 </table>