<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Vereinsuche\Module'                        => __DIR__ . '/Module.php',
    'Vereinsuche\Controller\VereinsucheController' => __DIR__ . '/src/Vereinsuche/Controller/VereinsucheController.php',
    'VereinsucheTest\Framework\TestCase'        => __DIR__ . '/tests/Vereinsuche/Framework/TestCase.php',
    'VereinsucheTest\SampleTest'                => __DIR__ . '/tests/Vereinsuche/SampleTest.php',
);
