<?php
$title = 'Athleten entfernen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Wollen sie wirklich den Athleten mit der Emailadresse '<?php echo $email; ?>' entfernen?
 </p>
<?php
$url = $this->url('athleteinsicht', array(
    'action' => 'delete',
    'id' => $id,
    'email' => $email
));
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="submit" name="del" value="Ja" class="button"/> <input type="submit"
			name="del" value="Nein" class="button"/>
	</div>
</form>