<html>

<body>

<?php 



require ("fpdf/fpdf.php");


class MyPDF extends FPDF{
    
    function Header(){
        
        $date = date("Y-m-d H:i:s");
        $this->SetFont("Helvetica","B",16);
        $this->Cell(0,20,"Athlet-Werbeaufträge Zuordnung:","B",1,"C");
    }
    
    
    function Footer(){
        
        $this->SetY(-20);
        $this->SetFont("Helvetica","B",8);
        $this->Cell(0,10,"Seite".$this->PageNo()."/{nb}","T",0,"R");
    }
}

$pdf=new MyPDF();
$pdf->AliasNbPages();
$pdf->AddPage();

$date = date("Y-m-d H:i:s");
$anzahl=count($inhalte);

$pdf->SetFont("Helvetica","BU",13);
$pdf->SetLineWidth(0,4);
$pdf->SetDrawColor(0,218,255);
$pdf->SetFillColor(192,192,192);
$pdf->SetTextColor(26,26,26);

$pdf->SetXY(10,50);

$pdf->Cell(30,10,"AthletId","LR",0,"C",1);
$pdf->Cell(40,10,"WerbeauftragID","LR",0,"C",1);
$pdf->Ln();



$pdf->SetFont("Helvetica","",5);
for ($i = 0; $i < $anzahl; $i++) {
    
    $pdf -> SetY(60);
    $pdf->Cell(30,10,$inhalte[$i]["Athletid"],"LR",0,"C",1);
    $pdf->Cell(40,10,$inhalte[$i]["Werbeauftragid"],"LR",0,"C",1);
    $pdf->Ln();
}

 



$pdf->Output("C:\Users\Fabi\Downloads"."\Athleten_Werbeauftrag_Zuordnung".$id.".pdf","F");

echo "PDF-Datein wurde erfolgreich im Verzeichnis 'Downloads' erstellt!";

?>
<p>
	<a
		href="<?php

echo $this->url('athleteinsicht', array(
    'action' => 'index'
));
?>">&Uumlbersicht</a>
</p>
</body>

</html>