<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Betreiber\Module'                        => __DIR__ . '/Module.php',
    'Betreiber\Controller\BetreiberController' => __DIR__ . '/src/Betreiber/Controller/BetreiberController.php',
    'BetreiberTest\Framework\TestCase'        => __DIR__ . '/tests/Betreiber/Framework/TestCase.php',
    'BetreiberTest\SampleTest'                => __DIR__ . '/tests/Betreiber/SampleTest.php',
);
