<?php
$title = 'Add Kind';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('kinder', array(
    'action' => 'add',
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('geburtsdatum'));
echo $this->formRow($form->get('geschlecht'));



// echo $this->formRow($form->get('bildname'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>
<p>
</p>