<?php
$title = 'Kinderliste';
$this->headTitle($title);
$form = $this->form;
$form->get('submit')->setAttribute('value', 'Buchen');
$form->prepare();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<table class="table">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Geburtsdatum</th>
		<th>Geschlecht</th>
		<th>Athletid</th>
		<th></th>
	</tr>
 <?php foreach ($kinder as $kind): 

 $form->setAttribute('action', $this->url('ergebnis', array(
     'action' => 'kind', 'id' => $event->getId(), 'kid' => $kind->getId()
 )));

 echo $this->form()->openTag($form);
 ?>
 <tr>
		<td><?php echo $this->escapeHtml($kind->getId()); ?></td>
            <td><?php echo $this->escapeHtml($kind->getName()); ?></td>
            <td><?php echo $this->escapeHtml($kind->getGeburtsdatum()); ?></td>
            <td><?php echo $this->escapeHtml($kind->getGeschlecht()); ?></td>
    		<td><?php echo $this->escapeHtml($kind->getAthletid()); ?></td>   
    		<td><a
            		href="<?php
            echo $this->url('kinder', array(
                'action' => 'delete',
                'id' => $kind->getId()
                   ));
            ?>">Delete</a></td> 	
             <td><?php echo $this->formRow($form->get('zahlungsart'));
        echo $this->formInput($form->get('submit'));?></td>	
 <?php endforeach; ?>
 </table>