<?php
$title = 'Meine Kinder';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
	<a
		href="<?php

echo $this->url('kinder', array(
    'action' => 'add'
));
?>">Kind hinzufügen</a>
</p>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Geburtsdatum</th>
		<th>Geschlecht</th>
		<th></th>
	</tr>
 <?php foreach ($kinder as $kind): ?>
 <tr>
            <td><?php echo $this->escapeHtml($kind->getName()); ?></td>
            <td><?php echo $this->escapeHtml($kind->getGeburtsdatum()); ?></td>
            <td><?php echo $this->escapeHtml($kind->getGeschlecht()); ?></td>
    		<td><a
            		href="<?php
            echo $this->url('kinder', array(
                'action' => 'delete',
                'id' => $kind->getId()
                   ));
            ?>">Delete</a></td> 		
 <?php endforeach; ?>
 </table>