<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Vereinbezahlung\Module'                        => __DIR__ . '/Module.php',
    'Vereinbezahlung\Controller\VeranstalterController' => __DIR__ . '/src/Vereinbezahlung/Controller/VereinbezahlungController.php',
    'VereinbezahlungTest\Framework\TestCase'        => __DIR__ . '/tests/Vereinbezahlung/Framework/TestCase.php',
    'VereinbezahlungTest\SampleTest'                => __DIR__ . '/tests/Vereinbezahlung/SampleTest.php',
);
