<?php
$title = 'Event bearbeiten';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$url = $this->url('event', array(
    'action' => 'edit',
    'id' => $id
));
$form->setAttribute('action', $url);
$form->get('submit')->setAttribute('value', 'Edit');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('veranstaltungsid'));?><br/>Name<?php
echo $this->formRow($form->get('name'));?><br/>PLZ<?php
echo $this->formRow($form->get('postleitzahl'));?><br/>Ort<?php
echo $this->formRow($form->get('ort'));?><br/>Strasse<?php
echo $this->formRow($form->get('strasse'));?><br/>Hausnummer<?php
echo $this->formRow($form->get('hausnummer'));?><br/>Gebühr<?php
echo $this->formRow($form->get('anmeldegebuehr'));?><br/>

<link href="/css/bootstrap-combined.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen"
     href="/css/bootstrap-datetimepicker.min.css">
<div id="datetimepicker" class="input-append date">
      <input type="text" name="datepicker" id="date" value="<?php if($event->getDatum())echo $event->getDatum(); ?>">
      <span class="add-on">
        <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      </span>
    </div>
    <script type="text/javascript"
     src="/js/jquery.min.js">
    </script> 
    <script type="text/javascript"
     src="/js/bootstrap.min.js">
    </script>
    <script type="text/javascript"
     src="/js/bootstrap-datetimepicker.min.js">
    </script>
    <script type="text/javascript"
     src="/js/locales/bootstrap-datetimepicker.de.js">
    </script>
    <script type="text/javascript">
      $('#datetimepicker').datetimepicker({
        format: 'yyyy-MM-dd hh:mm',
        language: 'de',
        startDate: new Date(),
        timePicker: false,
      });
    </script><br /><?php 
echo $this->formRow($form->get('geschlechtsbeschraenkung'));?><br/>Meisterschaft<?php
echo $this->formRow($form->get('meisterschaftsbeschraenkung'));?><br/>Beschreibung<?php
echo $this->formRow($form->get('beschreibung'));?><br/>Sportart<?php
echo $this->formRow($form->get('sportart'));?><br/>Teilnehmerlimit<?php
echo $this->formRow($form->get('teilnehmerlimit'));?><br/>Kategorie<?php
echo $this->formRow($form->get('kategorien'));?><br/>Minimum<?php
echo $this->formRow($form->get('altersminimum'));?><br/>Maximum<?php
echo $this->formRow($form->get('altersmaximum'));?>

<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);