<?php
use Zend\Filter\DateTimeFormatter;
$title = 'My event list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}


?>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Ort</th>
		<th>PLZ</th>
		<th>Strasse</th>
		<th>Hausnummer</th>
		<th>Datum</th>
		<th>Meisterschaft</th>
		<th>Geschlecht</th>
		<th>Gebuehr</th>
		<th>&nbsp;</th>
	</tr>
 <?php foreach ($events as $event): 
 $form = $this->form;
 $form->setAttribute('action', $this->url('ergebnis', array(
     'action' => 'anmelden', 'id' => $event->getId()
 )));
 $form->get('submit')->setAttribute('value', 'Buchen');
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
 <tr>
		<td><?php echo $this->escapeHtml($event->getName()); ?></td>
		<td><?php echo $this->escapeHtml($event->getOrt()); ?></td>
		<td><?php echo $this->escapeHtml($event->getPostleitzahl()); ?></td>
		<td><?php echo $this->escapeHtml($event->getStrasse()); ?></td>
		<td><?php echo $this->escapeHtml($event->getHausnummer()); ?></td>
		<td><?php echo $this->escapeHtml(DateTime::createFromFormat('Y-m-d H:i:s', $event->getDatum())->format('Y-m-d H:i')); ?></td>
		<td><?php echo $event->getMeisterschaftsbeschraenkung() ? $event->getMeisterschaftsbeschraenkung() : 'No'; ?></td>
		<td><?php echo $event->getGeschlechtsbeschraenkung() != NULL ? $event->getGeschlechtsbeschraenkung() : 'No'; ?></td>
		<td><?php echo $this->escapeHtml($event->getAnmeldegebuehr()); ?> &#8364;</td>
		<td></td>	
          <td><a href="<?php  
                 echo $this->url('kinder', array(
                     'action' => 'auswahl',
                        'id' => $athlet->id,
                     'ev' => $event->getId()
                   ));
                 ?>">
             Kind auswaehlen</a></td>   
        <td><?php echo $this->formRow($form->get('zahlungsart'));
        echo $this->formInput($form->get('submit'));?></td>     
        
        <?php
echo $this->form()->closeTag($form);
?>
     
 <?php endforeach; ?>
 </table>
 <p> Bitte beachten Sie, dass diese Anmeldung verbindlich ist und die Teilnehmergebuehr sofort abgebucht wird !