<?php
$title = 'Label beantragen';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

if ($this->flashMessenger()->hasMessages()) {
    
    echo '<div class="alert alert-info">';
    
    $messages = $this->flashMessenger()->getMessages();
    foreach ($messages as $message) {
        echo $message;
    }
    
    echo '</div>';
}

?>
<?php

if ($check != Null) {
    
    $form = $this->form;
    $form->setAttribute('action', $this->url('event', array(
        'action' => 'label',
        'id' => $eventid
    )));
    $form->get('submit')->setAttribute('value', 'Beantragen');
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('label'));
    
    ?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
    echo $this->form()->closeTag($form);
    ?>
<p></p>

<?php } else {?>

<h1><?php echo "Es wurden bereits alle Label Beantragt!"?></h1>
<?php }?>
<table>
 <?php if($Genehmigt!= NUll){?>
<?php

    foreach ($Genehmigt as $label) :
        ?>
<tr>
		<td><?php echo $this->escapeHtml($label->getLabelname()); ?></td>
		<td><img src="../../Labels/<?= $label->getLabelname()?>.jpg"
			width="90" height="90" />
		<hr></td>
		<td>Genehmigt</td>
	</tr>
 <?php
    
endforeach
    ;
}
?>
  <?php if($Beantragt!= NUll){?>
 <?php
    foreach ($Beantragt as $label) :
        ?>
<tr>
		<td><?php echo $this->escapeHtml($label->getLabelname()); ?></td>
		<td><img src="../../Labels/<?= $label->getLabelname()?>.jpg"
			width="125" height="125" />
		<hr></td>
		<td>Beantragt</td>
	</tr>
 <?php
    
endforeach
    ;
}
?>
 </table>