<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>

<div style="height: 500px; width: 100%; overflow: hidden">
	<img src="img/running.jpg" width="100%">
</div>
<div style="margin-top: -40px; margin-right: 40px; color: white; width: 100%; text-align: right;">
<a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>" class="button">Logout</a>
</div>


