
 <?php

 $title = 'Daten bearbeiten: ';
 $this->headTitle($title);
 ?>
 
 <h3><?php echo $this->escapeHtml($title); ?></h3>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'athlet',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
 
 <br/><legend><h4>Gegebenenfalls Felder ändern:<h4></legend><br/>

 <div>
 <?php
 echo $this->formHidden($form->get('id'));
 echo $this->formHidden($form->get('Kontostand'));
 echo $this->formHidden($form->get('Vorname'));
 ?> <br/>
 <?php
 echo $this->formHidden($form->get('Name')); 
 ?> <br/>
 <?php
 echo $this->formRow($form->get('Titel'));
 ?>
 <?php 
 echo $this->formRow($form->get('Zusatz'));
 ?> <br/>
 </div>
 <br/>
 
 
 <?php
 echo $this->formHidden($form->get('Geschlecht'));
 ?> <br/><br/>
 <?php
 echo $this->formHidden($form->get('Geburstag'));
 ?> <br/>
 <br/>
 
 <?php
 echo $this->formRow($form->get('Bezeichnung'));
 ?> <br/><br/>
 
 <?php
 echo $this->formRow($form->get('SportBezeichnung'));
 ?> <br/><br/>
 
 
 <?php
 echo $this->formRow($form->get('Werbung'));
 ?> <br/>
 
 
 <?php
 echo $this->formRow($form->get('Historie'));
 ?> <br/>
 
 
 <?php
 echo $this->formRow($form->get('Umkreis'));
 ?> <br/> <br/>
 
 
 <div>
 <?php
 echo $this->formRow($form->get('Strasse'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('Hausnummer'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('Postleitzahl'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('Ort'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('Land'));
 ?> <br/>
 </div>
 <br/>
 
 
 <div>
 <?php
 echo $this->formRow($form->get('tel1landauswahl_athlet'));
 //echo $this->formRow($form->get('vorwahltel1_athlet'));
 echo $this->formRow($form->get('Telefonnummer1'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('tel2landauswahl_athlet'));
 //echo $this->formRow($form->get('vorwahltel2_athlet'));
 echo $this->formRow($form->get('Telefonnummer2'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('tel3landauswahl_athlet'));
 //echo $this->formRow($form->get('vorwahltel3_athlet'));
 echo $this->formRow($form->get('Telefonnummer3'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('faxlandauswahl_athlet'));
 //echo $this->formRow($form->get('vorwahlfax_athlet'));
 echo $this->formRow($form->get('Fax'));
 ?> <br/><br/>
 
 <?php
 echo $this->formRow($form->get('Firma'));
 ?> <br/>
 </div>
 <br/>
 

 <div>
 <?php
 echo $this->formRow($form->get('name_athlet_bkih'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('IBAN'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('BIC'));
 ?> <br/>
 </div>
 <br/>
 
<!-- Darstellung in der Form Alex Giedt 16.12-->

  <?php $fileElement = $form->get('image-file'); ?>
  <?php echo $this->formLabel($fileElement); ?>
  <?php echo $this->formFile($fileElement); ?>
  <?php echo $this->formElementErrors($fileElement); ?>
<br/><br/>
 
 <div>
 <?php
 echo $this->formRow($form->get('Email'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('Passwort'));
 ?> <br/>
 <?php
 echo $this->formRow($form->get('pw2_athlet'));
 ?> <br/>
 </div>
 <br/>
 
 <?php
 echo $this->formSubmit($form->get('areg'));
 echo $this->form()->closeTag();
 ?>
 
 <!-- ab hier relevant für Zurücksetz-Button (PR, 13.12.14) -->
 <?php
 $form->setAttribute('action', $this->url('athlet', array('action' => 'aregreset')));
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>
 <br/>
 <?php
 echo $this->formSubmit($form->get('aregreset'));
 echo $this->form()->closeTag();
 ?>