<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Athletenhistorie\Module'                        => __DIR__ . '/Module.php',
    'Athletenhistorie\Controller\AthletenhistorieController' => __DIR__ . '/src/Athletenhistorie/Controller/AthletenhistorieController.php',
    'Athletenhistorie1Test\Framework\TestCase'        => __DIR__ . '/tests/Athletenhistorie/Framework/TestCase.php',
    'Athletenhistorie1Test\SampleTest'                => __DIR__ . '/tests/Athletenhistorie/SampleTest.php',
);
