<?php
$title = 'Suchergebnisse';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('search', array(
    'action' => 'index'
)));
$form->get('submit')->setAttribute('value', 'Suchen');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
?>
 <?php echo $this->formInput($form->get('submit')); ?>
<?php
echo $this->form()->closeTag($form);
?><br />
<table>

<td>
<a href="<?php  
                 echo $this->url('search', array(
                     'action' => 'erweitert'
                   ));
                 ?>">
             Erweiterte Suche </a></td> 
             <td>
<a href="<?php  
                 echo $this->url('search', array(
                     'action' => 'veranstaltung'
                   ));
                 ?>">
             Veranstaltungssuche </a></td>
</table> <br/>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Ort</th>
		<th class="searchmobile">PLZ</th>
		<th class="searchmobile">Datum</th>
		<th class="searchmobile">Gebuehr</th>
		<th class="searchmobile">&nbsp;</th>
	</tr>
 <?php foreach ($events as $event): ?>
 <tr>
		<td><a
			href="<?php
    
echo $this->url('event', array(
        'action' => 'show',
        'id' => $event->getId()
    ));
    ?>">
             <?php echo $this->escapeHtml($event->getName()); ?></a></td>
		<td><?php echo $this->escapeHtml($event->getOrt()); ?></td>
		<td class="searchmobile"><?php echo $this->escapeHtml($event->getPostleitzahl()); ?></td>
		<td class="searchmobile"><?php echo $this->escapeHtml(DateTime::createFromFormat('Y-m-d H:i:s', $event->getDatum())->format('Y-m-d H:i')); ?></td>
		<td class="searchmobile"><?php echo $this->escapeHtml($event->getAnmeldegebuehr()); ?> &#8364;</td>
                 <td class="searchmobile"><a href="<?php  
                 echo $this->url('ergebnis', array(
                     'action' => 'ergebnis',
                        'id' => $event->getId()
                   ));
                 ?>">
             Ergebnisse</a></td>
                 <td class="searchmobile"><a href="<?php  
                 echo $this->url('bewertung', array(
                     'action' => 'durchschnitt',
                        'id' => $event->getId()
                   ));
                 ?>">
             Bewertungen</a></td>      
 <?php endforeach; ?>
 </table>