<?php
$title = 'Veranstaltung suchen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<td>
<a href="<?php  
                 echo $this->url('search', array(
                     'action' => 'index'
                   ));
                 ?>">
             Eventsuche</a></td> 
             <td>
             
<a href="<?php  
                 echo $this->url('search', array(
                     'action' => 'erweitert'
                   ));
                 ?>">
             Erweiterte Eventsuche</a></td>

<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('search', array(
    'action' => 'veranstaltung'
)));
$form->get('submit')->setAttribute('value', 'Suchen');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
?>
 <?php echo $this->formInput($form->get('submit')); ?>
<?php
echo $this->form()->closeTag($form);
?>

<?php if($veranstaltungen){?>

<?php if($veranstaltungen->count()==0){?>
    <h3><?php print("Keine Veranstaltungen f&uuml;r ihre Suche gefunden.");?> </h3>
                <?php  } else {?>


<table class="table">
 <?php foreach ($veranstaltungen as $veranstaltung): ?>
 	<tr>
		<th>Veranstaltungsname:</th>
	
		<td><a
			href="<?php
    
echo $this->url('veranstaltung', array(
        'action' => 'profil',
        'id' => $veranstaltung->getId()
    ));
    ?>">
            <?php echo $this->escapeHtml($veranstaltung->getName()); ?></a></td>
		<td><p>
	
</p></td>         	
 <?php 
 $events = $eventmapper->Eventver($veranstaltung->getId());
 foreach ($events as $event  ): 
 if($event->getVeranstaltungsid()==$veranstaltung->getId()){
 ?>
 
 
 <tr>
		<td><a
			href="<?php
    
echo $this->url('event', array(
        'action' => 'show',
        'id' => $event->getId()
    ));
    ?>">
             <?php echo $this->escapeHtml($event->getName()); ?></a></td>
		<td><?php echo $this->escapeHtml($event->getOrt()); ?></td>
		<td><?php echo $this->escapeHtml($event->getPostleitzahl()); ?></td>
		<td><?php echo $this->escapeHtml(DateTime::createFromFormat('Y-m-d H:i:s', $event->getDatum())->format('Y-m-d H:i')); ?></td>
		<td><?php echo $this->escapeHtml($event->getAnmeldegebuehr()); ?> &#8364;</td>
                 <td><a href="<?php  
                 echo $this->url('ergebnis', array(
                     'action' => 'ergebnis',
                        'id' => $event->getId()
                   ));
                 ?>">
             Ergebnisse</a></td>    
                 <td><a href="<?php  
                 echo $this->url('bewertung', array(
                     'action' => 'durchschnitt',
                        'id' => $event->getId()
                   ));
                 ?>">
             Bewertungen</a></td>  
 <?php };

 endforeach; ?>
 <p></p>
 <?php endforeach; ?>
 </table>
 <?php }}?>