<?php
$title = 'Profilübersicht Verein';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
  <p>
     <a href="<?php echo $this->url('verein', array('action'=>'wechsel', 'id' => $verein->id));?>">Vereinsadminwechsel</a>
 </p>
  <p>
      <a href="<?php echo $this->url('event', array('action'=>'aktuell'));?>">Veranstaltungen</a>
 </p>
<!-- Steuerung der Navigation erfolgt über Application/view/layout/layout.phtm -->
<table class="table">
 <tr>
     <th>Name</th>
     <th>Email</th>
     <th>Strasse</th>
     <th>Hausnummer</th>
     <th>Postleitzahl</th>
     <th>Ort</th>
     <th>Bankkontoinhaber</th>
     <th>Vereinsvertreter</th>
     <th>&nbsp;</th>
 </tr>
 <tr>
     <td><?php echo $this->escapeHtml($verein->Name);?></td>
     <td><?php echo $this->escapeHtml($verein->Email);?></td>
     <td><?php echo $this->escapeHtml($verein->Strasse);?></td>
     <td><?php echo $this->escapeHtml($verein->Hausnummer);?></td>
     <td><?php echo $this->escapeHtml($verein->Postleitzahl);?></td>
     <td><?php echo $this->escapeHtml($verein->Ort);?></td>
     <td><?php echo $this->escapeHtml($verein->Bankkontoinhaber);?></td>
     <td><?php echo $this->escapeHtml($verein->Vereinsvertreter);?></td>
     
    
     <td>
         <a href="<?php echo $this->url('verein',
             array('action'=>'edit', 'id' => $verein->id));?>">Detailansicht/ Bearbeiten</a>
                  </td>
 </tr>
 </table>
<?php

?>