<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
 'Mitarbeitereventansicht\Module'                        => __DIR__ . '/Module.php',
    'Mitarbeitereventansicht\Controller\MitarbeitereventansichtController' => __DIR__ . '/src/Mitarbeitereventansicht/Controller/MitarbeitereventansichtController.php',
    'MitarbeitereventansichtTest\Framework\TestCase'        => __DIR__ . '/tests/Mitarbeitereventansicht/Framework/TestCase.php',
    'MitarbeitereventansichtTest\SampleTest'                => __DIR__ . '/tests/Mitarbeitereventansicht/SampleTest.php',
);
