<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Ergebnis\Module'                        => __DIR__ . '/Module.php',
    'Ergebnis\Controller\ErgebnisController' => __DIR__ . '/src/Ergebnis/Controller/ErgebnisController.php',
    'VeranstaltungTest\Framework\TestCase'        => __DIR__ . '/tests/Veranstaltung/Framework/TestCase.php',
    'VeranstaltungTest\SampleTest'                => __DIR__ . '/tests/Veranstaltung/SampleTest.php',
);
