<?php
$title = 'Add new Veranstalter';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('veranstalter', array(
    'action' => 'add'
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('vorname'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('passwort'));
echo $this->formRow($form->get('iban'));
echo $this->formRow($form->get('bic'));
echo $this->formRow($form->get('verifiziert'));
echo $this->formRow($form->get('firmenname'));
echo $this->formRow($form->get('strasse'));
echo $this->formRow($form->get('hausnummer'));
echo $this->formRow($form->get('postleitzahl'));
echo $this->formRow($form->get('ort'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>
<p>
	<a
		href="<?php

echo $this->url('veranstalter', array(
    'action' => 'index'
));
?>">Uebersicht</a>
</p>