<?php
$title = 'Suche: Vereinsbuchung';
$this->headTitle($title);
?>
<h1><u>Nach einer Bezahlung suchen</u></h1>

<form action="search">
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    <tr>
      <td align="right">VereinsID:</td>
      <td><input name="id" type="text" size="30" maxlength="30"></td>
    </tr>
    <tr>
      <td align="right">Verwendungszweck:</td>
      <td><input name="useid" type="text" size="30" maxlength="30"></td>
    </tr>
      <td align="right"></td>
      <td>
        <input type="submit" value=" Absenden" name="absenden">
    </tr>
  </table>
</form>

<table class="table" border="2" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
	<tr bgcolor=#F7FAAC>
		<th>ID</th>
		<th>Vereins ID</th>
		<th>Iban</th>
		<th>Bic</th>
		<th>Wert</th>
		<th>Datum</th>
		<th>Verwendungszweck</th>
		<th>Verwendungsart</th>
		<th>Weiter&uumlberweisen</th>
		<th>Zur&uumlck&uumlberweisen</th>
	</tr>
 <?php
 if($vereinbezahlungen!=NULL){
 foreach ($vereinbezahlungen as $vereinbezahlung): ?>
 <tr>
		<td> <?php echo $this->escapeHtml($vereinbezahlung->getId()); ?></td>
            <td><?php echo $this->escapeHtml($vereinbezahlung->getVereinid()); ?></td>
    		<td><?php echo $this->escapeHtml($vereinbezahlung->getIban()); ?></td>
    		<td><?php echo $this->escapeHtml($vereinbezahlung->getBic()); ?></td>
    		<td><?php echo $this->escapeHtml($vereinbezahlung->getWert()); ?>&#8364;</td>
    		<td><?php echo $this->escapeHtml($vereinbezahlung->getDatum()); ?></td>
    		<td><?php echo $this->escapeHtml($vereinbezahlung->getVerwendungszweck()); ?></td>
    		<td><?php echo $this->escapeHtml($vereinbezahlung->getVerwendungsart()); ?></td>
      
             
             
             <td><a
			href="<?php
    
echo $this->url('vereinbezahlung', array(
        'action' => 'forward',
        'id' => $vereinbezahlung->getId(),
        'vereinid' => $vereinbezahlung->getVereinid(),
        'wert'=> $vereinbezahlung->getWert(),
        'useid' => $vereinbezahlung->getVerwendungszweck()
        
        
    ));
    ?>"><img src="http://cdns2.freepik.com/fotos-kostenlos/pfeil-rechts-grun-clip-art_427400.jpg" width="70" height="40" ></a></td>

    
    
  
  
    <td><a
			href="<?php
    
echo $this->url('vereinbezahlung', array(
        'action' => 'back',
        'id' => $vereinbezahlung->getId(),
        'vereinid' => $vereinbezahlung->getVereinid(),
        'wert'=> $vereinbezahlung->getWert(),
       
    ));
    ?>"><img src="http://www.care4media.ch/Portals/627/images/reseller/pfeillinks.jpg" width="70" height="40" ></a></td>
			
 <?php endforeach;
 } ?>
 </table>
 
 <p>
	<a
		href="<?php

echo $this->url('vereinbezahlung', array(
    'action' => 'index'
));
?>">&Uumlbersicht</a>
</p>