 <?php
 $title = 'Lizenz fuer ein Event eintragen:';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('anfragen', array('action' => 'addlizenz')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('eventid'));
 echo $this->formRow($form->get('lizenz'));
 ?>
 <div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>