<h1>Das soll so aussehen...</h1>
<?php
$title = 'Bestaetigen/Ablehnen von Cash-Back-Aktionen:';
$this->headTitle($title);
?>
<br>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
	<tr>
		<th>ID</th>
		<th>Anfang</th>
		<th>Ende</th>
		<th>Wert</th>
		<th>EventID</th>
		<th></th>
	</tr>
 <tr>
            <td>28</td>
            <td>10.Januar</td>
            <td>15.Januar</td>
            <td>2</td>
            <td>2</td>
            <td><a href="">Loeschen</a></td>
 </table>