<?php
$title = 'Anfragen verwalten';
$this->headTitle($title);
?>
<h1><u><?php echo $this->escapeHtml($title); ?></u></h1>
<hr width=“15“ size=“1“ noshade=“noshade“ align=“left“ />


<form action=labeleventzuordnung>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">

    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Label-Anfragen verwalten" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<form action=vereinsadminaendern>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Vereinsadministrator-Anfragen verwalten" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<form action=cashbackmultiplikator/edit>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Cash-Back-Aktionen verwalten" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<form action=lizenz>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Lizenzen zu Events eintragen" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>

<form action=veranstalterverifizieren>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">

    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Veranstalter verifizieren" style="width: 290px; height: 30px" class="button">
        
      </td>
    </tr>
  </table>
</form>
