<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Gutscheincode\Module'                        => __DIR__ . '/Module.php',
    'Gutscheincode\Controller\GutscheincodeController' => __DIR__ . '/src/Gutscheincode/Controller/GutscheincodeController.php',
    'GutscheincodeTest\Framework\TestCase'        => __DIR__ . '/tests/Gutscheincode/Framework/TestCase.php',
    'GutscheincodeTest\SampleTest'                => __DIR__ . '/tests/Gutscheincode/SampleTest.php',
);
