<?php
$title = 'Weiterueberweisen gruppiert: Sicherheitsabfrage';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Sind sie sich sicher dass sie die Buchung mit der an den Empfaenger weiterueberweisen wollen?
 </p>
<?php



$url = $this->url('athletenbezahlung', array(
    'action' => 'forwardgroup',
    'wert' => $wert,
    'useid' => $useid,
));
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="submit" name="del" value="Yes" /> <input type="submit"
			name="del" value="No" />
	</div>
</form>