<?php
use Zend\Filter\DateTimeFormatter;
$title = 'alle Athletenbuchungen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a
		href="<?php

echo $this->url('athletenbezahlung', array(
    'action' => 'search'
));
?>">nach Zahlungen suchen</a>
</p>
<p>
	<a
		href="<?php

echo $this->url('athletenbezahlung', array(
    'action' => 'group'
));
?>">nach Verwendungszweck gruppieren</a>
</p>





<table class="table">
	<tr>
		<th>ID</th>
		<th>Iban</th>
		<th>Bic</th>
		<th>Datum</th>
		<th>AthletenID</th>
		<th>Wert</th>
		<th>Verwendungszweck</th>
		<th>Verwendungsart</th>
		<th>&nbsp;</th>
		<th></th>
	</tr>
 <?php foreach ($athletenbezahlungen as $athletenbezahlung): ?>
 <tr>
       <td> <?php echo $this->escapeHtml($athletenbezahlung->getId()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getIban()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getBic()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getDate()); ?></td>
    		
    		
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getAthletid()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getWert()) ?>&#8364;</td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getVerwendungszweck()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getVerwendungsart()); ?></td>
    		
    	
    	
    		<td><a
			href="<?php
    
echo $this->url('athletenbezahlung', array(
        'action' => 'forward',
        'id' => $athletenbezahlung->getId(),
        'athletid' => $athletenbezahlung->getAthletid(),
        'wert'=> $athletenbezahlung->getWert(),
        'useid' => $athletenbezahlung->getVerwendungszweck()
    ));
    ?>">Weiterüberweisen</a></td>

    
    
  
  
    <td><a
			href="<?php
    
echo $this->url('athletenbezahlung', array(
        'action' => 'back',
        'id' => $athletenbezahlung->getId(),
        'athletid' => $athletenbezahlung->getAthletid(),
        'wert'=> $athletenbezahlung->getWert()
    ));
    ?>">Zurueckueberweisen</a></td>

    					
 <?php endforeach; ?>
 </table>