<?php
$title = 'Veranstaltung bearbeiten';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('veranstaltung', array(
    'action' => 'edit','id' =>  $veranstaltung->getId()
)));
$form->get('submit')->setAttribute('value', 'Bearbeiten');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="searchtitle">Name:</div>
<?php

echo $this->formRow($form->get('name'));

?>
<div class="clear"></div>

<br /><br />
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div><br /><br />
<?php
echo $this->form()->closeTag($form);
?>

<p>
	<a
		href="<?php

echo $this->url('event', array(
    'action' => 'index'
));
?>">Uebersicht</a><br />

</p>