<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Veranstaltungen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<p>
	<a
		href="<?php

echo $this->url('veranstaltung', array(
    'action' => 'add'
));
?>">Add new item</a>
</p>

<table class="table">
	<tr>
		<th></th>
		<th>Name</th>
        <th>Bild</th>
        <th>Bild hinzufügen</th>
        <th>Historie</th>
        <th>Profil</th>
	</tr>
 <?php foreach ($veranstaltungen as $veranstaltung): ?>
 <tr>
		<td><?php if($veranstaltung->getStatus() == 0)
		{?>
		    <a
			href="<?php
    
                echo $this->url('veranstaltung', array(
                'action' => 'public',
                'id' => $veranstaltung->getId()
    ));
    ?>">
             goPublic</a>
		    
		<?php }?></td>
		<td><a
			href="<?php
    
echo $this->url('veranstaltung', array(
        'action' => 'show',
        'id' => $veranstaltung->getId()
    ));
    ?>">
             <?php echo $this->escapeHtml($veranstaltung->getName()); ?></a></td>
    <td><img src="img/<?= $bild->getLink1($veranstaltung->getBildid())?>" width="100" height="100" alt="<?= $veranstaltung->getName()?>"/></td>         
	<td><a href="<?php  
                 echo $this->url('bild', array(
                     'action' => 'veranstaltung',
                        'id' => $veranstaltung->getId()
                   ));
                 ?>">
             <img src="img/add.png" width="30" height="30" alt="add"></a></td>
	<td><a href="<?php  
                 echo $this->url('veranstaltung', array(
                     'action' => 'hist',
                        'id' => $veranstaltung->getId()
                   ));
                 ?>">
             <img src="img/historie.png" width="30" height="30" alt="historie"></a></td>	
    	<td><a href="<?php  
                 echo $this->url('veranstaltung', array(
                     'action' => 'profil',
                        'id' => $veranstaltung->getId()
                   ));
                 ?>">
             <img src="img/profil.png" width="30" height="30" alt="profil"></a></td>	         	
 <?php endforeach; ?>
 </table>