<?php
use Zend\Filter\DateTimeFormatter;
$title = 'alle Athletenbuchungen';
$this->headTitle($title);
?>
<h1><u>Liste aller Athletenbezahlungen</u></h1>
<form action=athletenbezahlung/search>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Nach Zahlungen suchen" style="width: 320px; height: 30px">
        
      </td>
    </tr>
  </table>
</form>

<form action=athletenbezahlung/group>
  <table border="0" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0">
    
    <tr>
      <td align="right"></td>
      <td>
        <input type="submit" value="Zahlungen nach Verwendungszweck gruppieren" style="width: 320px; height: 30px">
        
      </td>
    </tr>
  </table>
</form>


<table class="table" border="2" cellpadding="5" cellspacing="0" bgcolor="#E0E0E0" rules="groups" >
	<tr bgcolor=#F7FAAC> 
		<th>ID</th>
		<th>Iban</th>
		<th>Bic</th>
		<th>Datum</th>
		<th>AthletenID</th>
		<th>Wert</th>
		<th>Verwendungszweck</th>
		<th>Verwendungsart</th>
		<th>Weiter&uumlberweisen</th>
		<th>Zur&uumlck&uumlberweisen</th>
	</tr>
 <?php foreach ($athletenbezahlungen as $athletenbezahlung): 

 ?>
 <tr>
            <td> <?php echo $this->escapeHtml($athletenbezahlung->getId()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getIban()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getBic()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getDatum());?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getAthletid()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getWert()) ?>&#8364;</td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getVerwendungszweck()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getVerwendungsart()); ?></td>
    		
    	
    	
    		<td><a
			href="<?php
    
echo $this->url('athletenbezahlung', array(
        'action' => 'forward',
        'id' => $athletenbezahlung->getId(),
        'athletid' => $athletenbezahlung->getAthletid(),
        'wert'=> $athletenbezahlung->getWert(),
        'useid' => $athletenbezahlung->getVerwendungszweck()
    ));
    ?>"><img src="http://cdns2.freepik.com/fotos-kostenlos/pfeil-rechts-grun-clip-art_427400.jpg" width="70" height="40" ></a></td>

    
    
  
  
    <td><a
			href="<?php
    
echo $this->url('athletenbezahlung', array(
        'action' => 'back',
        'id' => $athletenbezahlung->getId(),
        'athletid' => $athletenbezahlung->getAthletid(),
        'wert'=> $athletenbezahlung->getWert()
    ));
    ?>"><img src="http://www.care4media.ch/Portals/627/images/reseller/pfeillinks.jpg" width="70" height="40" ></a></td>

    					
 <?php endforeach; ?>
 </table>