<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Kontobewegungen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>







<table class="table">
	<tr>
		<th>Iban</th>
		<th>Bic</th>
		<th>Datum</th>
		<th>Betrag</th>
		<th>Verwendungszweck</th>
		<th>Verwendungsart</th>
		<th>&nbsp;</th>
		<th></th>
	</tr>
 <?php foreach ($athletenbezahlungen as $athletenbezahlung): ?>
 <tr>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getIban()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getBic()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getDatum()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getWert()) ?>&#8364;</td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getVerwendungszweck()); ?></td>
    		<td><?php echo $this->escapeHtml($athletenbezahlung->getVerwendungsart()); ?></td>
    		
    	

    					
 <?php endforeach; ?>
 </table>