<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Kinder\Module'                        => __DIR__ . '/Module.php',
    'Kinder\Controller\KinderController' => __DIR__ . '/src/Kinder/Controller/KinderController.php',
    'VeranstaltungTest\Framework\TestCase'        => __DIR__ . '/tests/Veranstaltung/Framework/TestCase.php',
    'VeranstaltungTest\SampleTest'                => __DIR__ . '/tests/Veranstaltung/SampleTest.php',
);
