<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
 'Werbeauftrag\Module'                        => __DIR__ . '/Module.php',
    'Werbeauftrag\Controller\WerbeauftragController' => __DIR__ . '/src/Werbeauftrag/Controller/WerbeauftragController.php',
    'WerbeauftragTest\Framework\TestCase'        => __DIR__ . '/tests/Werbeauftrag/Framework/TestCase.php',
    'WerbeauftragTest\SampleTest'                => __DIR__ . '/tests/Werbeauftrag/SampleTest.php',
);
