 <?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Neuen Gutscheincode erstellen';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('gutscheincode', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 //echo $this->formRow($form->get('gutscheincode')); //normal: fromHidden
 echo $this->formRow($form->get('wert'));
 //echo $this->formRow($form->get('status'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 