 <?php
 // module/Gutscheincode/view/Gutscheincode/Gutscheincode/index.phtml:

 $title = 'Meine Gutscheincodes';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
  <table class="table">
 <tr>
     <th>AthletID</th>
     <th>Kontostand</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($athleten as $athlet) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($athlet->id);?></td>
     <td><?php echo $this->escapeHtml($athlet->wert);?></td>
     <td>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>