<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Warenkorb';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

	
<table class="table">
	<tr>
		<th>Artikelid</th>
		<th>Status</th>
		<th>Datum</th>
		<th>Veranstalterid</th>
		<th>Menge</th>
		<th>&nbsp;</th>
		<th></th>
	</tr>
 <?php foreach ($bestellungen as $bestellung): ?>
 <tr>
		    <td><?php echo $this->escapeHtml($artikel->getShop($bestellung->getArtikelid())->getArtikelname()); ?></td>
            <td><?php echo $this->escapeHtml($bestellung->getStatus()); ?></td>
            <td><?php echo $this->escapeHtml($bestellung->getDatum()); ?></td>
            <td><?php echo $this->escapeHtml($bestellung->getVeranstalterid()); ?></td>
            <td><?php echo $this->escapeHtml($bestellung->getMenge()); ?></td>
 <?php endforeach; ?>
 </table>

<div class="clear" style="height: 50px;"></div>

   	<a href="<?php echo $this->url('shop', array('action' => 'shopve')); ?>" class="button" style="float: left;">Zurück zum Shop</a>
	<a href="<?php echo $this->url('shop', array('action' => 'bestellen'));?>" class="button" style="float: right">Diese Artikel verbindlich bestellen</a>
<div class="clear"></div>