<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Shop aus Sicht des Betreibers';
$this->headTitle($title);
use Zend\Form\Element;

$element = new Element\Image('my-image');
$element->setAttribute('src', 'bild/PNG_transparency_demonstration_1.png');
$test = dirname(__DIR__);
?>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-info">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a
		href="<?php

echo $this->url('shop', array(
    'action' => 'add'
));
?>">Neuen Artikel hinzufuegen</a>
	<a
		href="<?php

echo $this->url('shop', array(
    'action' => 'orderbetreiber'
));
?>">Bestellungen ansehen</a>
</p>
<table class="table">
	<tr>
		<th>Name</th>
		<th>Preis</th>
		<th>Bild</th>
        		<th>Bild hochladen</th>
                <th>Artikel bearbeiten</th>
                <th>Artikel löschen</th>
		<th>&nbsp;</th>
		<th></th>
	</tr>
 <?php foreach ($shops as $shop): ?>
 <tr>
            <td><?php echo $this->escapeHtml($shop->getArtikelname()); ?></td>
            <td><?php echo $this->escapeHtml($shop->getArtikelpreis()); ?></td>
            <td><img src="img/<?= $bild->getLink($shop->getArtikelbildid())?>" width="100" height="100" alt="<?= $shop->getArtikelname()?>"/></td>
            <td><a href="<?php  
                 echo $this->url('bild', array(
                     'action' => 'artikelbild',
                        'id' => $shop->getId()
                   ));
                 ?>">
             <img src="img/add.png" width="30" height="30" alt="add"></a></td>
                         <td><a href="<?php  
                 echo $this->url('shop', array(
                     'action' => 'edit',
                        'id' => $shop->getId()
                   ));
                 ?>">
             <img src="img/edit.png" width="30" height="30" alt="edit"></a></td>
                                      <td><a href="<?php  
                 echo $this->url('shop', array(
                     'action' => 'delete',
                        'id' => $shop->getId()
                   ));
                 ?>">
            <img src="img/delete.png" width="30" height="30" alt="delete"></a></td>
 <?php endforeach; ?>
 </table>