<?php
use Zend\Filter\DateTimeFormatter;
$title = 'Warenkorb';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<pre><?php print_r($bestellungen)?></pre>
<table class="table">
	<tr>
		<th>Artikelid</th>
		<th>Status</th>
		<th>Datum</th>
		<th>Veranstalterid</th>
		<th>Menge</th>
		<th>&nbsp;</th>
		<th></th>
	</tr>
 <?php foreach ($bestellungen as $bestellung): ?>
  <?php $art = $artikel->getShop($bestellung->getArtikelid());?>
 <tr>
		    <td><?php echo $this->escapeHtml($art->getArtikelname()); ?></td>
            <td><?php echo $this->escapeHtml($bestellung->getStatus()); ?></td>
            <td><?php echo $this->escapeHtml($bestellung->getDatum()); ?></td>
            <td><?php echo $this->escapeHtml($bestellung->getVeranstalterid()); ?></td>
            <td><?php echo $this->escapeHtml($bestellung->getMenge()); ?></td>
 <?php endforeach; ?>
 </table>
    <p>
	<a
		href="<?php

echo $this->url('shop', array(
    'action' => 'shopve'));
?>">Zurueck zum Shop</a>
</p>